// this object is used to map movie genres to TailwindCSS colors (in order to display genre badges with different colors)

export const genreColors: { [key: string]: string } = {
  Action: "bg-lime-900",
  Adventure: "bg-cyan-900",
  Animation: "bg-pink-600",
  Biography: "bg-blue-950",
  Comedy: "bg-orange-600",
  Crime: "bg-yellow-600",
  Drama: "bg-slate-800",
  Family: "bg-violet-800",
  Fantasy: "bg-fuchsia-700",
  "Film-Noir": "bg-neutral-950",
  History: "bg-slate-600",
  Horror: "bg-red-800",
  Music: "bg-orange-900",
  Musical: "bg-teal-800",
  Mystery: "bg-amber-600",
  Romance: "bg-pink-800",
  "Sci-Fi": "bg-sky-800",
  Sport: "bg-green-700",
  Thriller: "bg-slate-700",
  War: "bg-stone-700",
  Western: "bg-amber-800",
};
